{% set name = "flask-rest-api" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea2236bd273323ddd641608340840f9b96148c51e6ad0cc7fdc3762b8ac2cf31

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec
    - flask
    - marshmallow
    - python >=3
    - webargs
    - werkzeug

test:
  imports:
    - flask_rest_api

about:
  home: https://github.com/Nobatek/flask-rest-api
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow'
  doc_url: https://flask-rest-api.readthedocs.io
  dev_url: https://github.com/Nobatek/flask-rest-api

extra:
  recipe-maintainers:
    - mcs07
