travis:
  secure:
    BINSTAR_TOKEN: IZGViyXFiiFc0Dw/09R1O6arg/EwJDKCGfPp5FbpoqX2nqVXtygokcccMbo8czZGW8Qg8ro3wDRsBaxKS3IZZ6pL0nDORLaF0Onhzg9uf1Fm/JN0b0Ht2EjfkwsnqnRByQiNbCUIm5o4nsm9WX05fS1XivqiTpSF10NIkgmgPjO1MDsAitd//NNas7dZGqZ7OxErrz0k5yYVNvGdeAihyFregyrrMkAkG/do1JEhODGo878/P++NKazeOdXJIfOaNPK4P2ePhqYgYtJAiaBAn6d8O7k6gSCYX0vN0z9NDwJfi7GnPo3U40Szo+9VRPLcQaOhkArY1TsjFnR5V86EPBwhCLm+h/c8I4tmZNmrZnoRvCGjGV8sug3KS3wii0j2iEkWvqV7T4AdKXxRq3CmEptSx7NKLMmVQWI5ilkA5tuxZ7BLGhrdtYTbpu2PBPv1zHMimOxJP6A16VBAFvCLTO8GtFU+RPeVgs7/xHLPp1Vasi4mEhoEFtRnJGeEO9sSCMzoejYCKu4jWbpzoQP1ZoTu0Zj8JS9FAQsnihSyhOM4UQVeW17LVVWZ0QXknSIpHLJsKOt4Mzma+PGzlSOsfYKTVAqnLGV5DuQJIlwap0X53m8clcs2WMAIeRmIKMhprGuTG1tYWbYJGvQMkC3pVHvOeov1mool7Kt0XGCbJt8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
